import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      sm: "700px",
      md: "900px",
      lg: "1060px",
      xl: "1200px",
    },
    extend: {
      colors: {
        "trails-red": "#E85355",
        "trails-blue": "#2C45E5",
        "nav-search": "#CBCBCB",
        "hero-shadow": "#353535",
        "nav-carousal": "#9B9B9B",
        "hero-desc": "#D7D7D7",
        "genre": "#6F6F6F",
        "hero-trailer": "#CA2629",
        "light-nav": "#1D2599",
        "light-plus-btn": "#343434",
        "plus-btn": "#363636",
        "light-genre-font": "#414141",
        "genre-font": "#A8A8A8",
        "light-carousal-btn": "#3D3D3D",
        "carousal-btn": "#C0C0C0",
        "light-footer-circle": "#474747",
        "footer-circle": "#A2A2A2",
        "light-footer-rights": "#3F3F3F",
        "footer-rights": "#AAAAAA",
        "light-dropdown": "#E4E4E4",
        "dropdown": "#2D2D2D",
        "light-dropdown-hover": "#D5D5D5",
        "search-box": "#212121",
        "dropdown-hover": "#373737",
        "light-dropdown-input": "#DADADA",
        "light-dropdown-input2": "#D3D3D3",
        "login-input": "#363636",
        "light-stroke": "#525252",
        "light-screen-shadow": "#212121",
        "light-search-font": "#939393",
        "light-input-font": "#868686",
        "light-search-genres-font": "#3B3B3B",
        "search-genres-font": "#C1C1C1",
        "watchlist": "#121212",
        "dropdown-underline": "#808080",
        "checked": "#2C2C2C",
        "checked-stroke": "#959595",
        "white2": "#CFCFCF",
        "white3": "#DCDCDC",
        "pagination_disable": "#7B7B7B",
        "bullet-circle": "#878787",
        "persons-card-role": "#3A3A3A",
        "person-details-data": "#5C5C5C",
        "light-table-heading-font": "#585858",
        "light-my-list-description": "#1F1F1F",
        "light-user-states-font": "#656565",
        "light-profile-dropdown-username": "#808080",
        "profile-dropdown-username": "#B0B0B0",
        "light-give-a-rating-font": "#5D5D5D",
        "light-unfill-star": "#717171",
        "search": "#EAEAEA",
        "light-logout-font": "#FF0005",
        "dark": "#212121",
        "dark2": "#171717",
        "light-create-new-btn": "#262626",
        "create-new-btn": "#18181b",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        border: "hsl(var(--border))",
        ring: "hsl(var(--ring))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
      },
      fontFamily: {
        poppins: ["var(--font-poppins)", "system-ui", "sans-serif"],
        inter: ["var(--font-inter)", "system-ui", "sans-serif"],
        akshar: ["var(--font-akshar)", "system-ui", "sans-serif"],
        monda: ["var(--font-monda)", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
