import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      sm: "700px",
      md: "900px",
      lg: "1060px",
      xl: "1200px",
    },
    extend: {
      colors: {
        "trails-red": "#E85355",
        "trails-blue": "#2C45E5",
        "nav-search": "#CBCBCB",
        "hero-shadow": "#353535",
        "nav-carousal": "#9B9B9B",
        "hero-desc": "#D7D7D7",
        "genre": "#6F6F6F",
        "hero-trailer": "#CA2629",
        "light-nav": "#1D2599",
        "light-plus-btn": "#343434",
        "plus-btn": "#313131",
        "light-genre-font": "#414141",
        "genre-font": "#A8A8A8",
        "light-carousal-btn": "#3D3D3D",
        "carousal-btn": "#C0C0C0",
        "light-footer-circle": "#474747",
        "footer-circle": "#A2A2A2",
        "light-footer-rights": "#3F3F3F",
        "footer-rights": "#AAAAAA",
        "light-dropdown": "#E4E4E4",
        "light-dropdown-hover": "#CDCDCD",
        "light-dropdown-input": "#DADADA",
        "light-stroke": "#525252",
        "light-screen-shadow": "#212121",
        "light-search-font": "#939393",
        "light-input-font": "#868686",
        "light-search-genres-font": "#3B3B3B",
        "watchlist": "#121212",
        "checked": "#2C2C2C",
        "checked-stroke": "#959595",
        "dark": "#212121",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        border: "hsl(var(--border))",
        ring: "hsl(var(--ring))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
      },
      fontFamily: {
        poppins: ["var(--font-poppins)", "system-ui", "sans-serif"],
        inter: ["var(--font-inter)", "system-ui", "sans-serif"],
        akshar: ["var(--font-akshar)", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
